name = "auto-reaction-bot"
main = "api/worker.js"
compatibility_date = "2024-06-02"

[vars]
BOT_TOKEN = "7818588156:AAG5pwQ7L80dDuyXZS4xOVTH7KlQdmCrPaQ"
BOT_USERNAME = "tabasom_ReactionBOT"
EMOJI_LIST = "ğŸ‘â¤ğŸ”¥ğŸ¥°ğŸ‘ğŸ‰ğŸ¤©ğŸ™ğŸ‘ŒğŸ•ŠğŸ˜ğŸ³â¤â€ğŸ”¥ğŸ’¯âš¡ğŸ†"
RANDOM_LEVEL = "2"
RESTRICTED_CHATS = ""
